language: ruby

rvm:
 - 2.1.5

branches:
  only:
    - dev/chloe

before_install:
  - cd ./chloe/auto_stock_server/

before_script:
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rspec
