sudo: required

language: ruby

cache:
  bundler: true

rvm:
  - 2.1.5

services:
  - postgresql
addons:
  postgresql: '9.6'

branches:
  only:
    - dev/wayne

before_install:
  # go to project folder
  - cd ./wayne/stock_api_server/
  - cp config/database.travis.yml config/database.yml

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:drop db:create db:migrate RAILS_ENV=test

script:
  - bundle exec rspec spec