sudo: required

language: ruby

cache:
  bundler: true

rvm:
  - 2.1.5

services:
  - postgresql

branches:
  only:
    - dev/wayne

before_script:
  - psql -c 'create database stock_api_server_test;' -U postgres
  # go to project folder
  - cd ./wayne/stock_api_server/
  # change the db connection
  - cp config/database.travis.yml config/database.yml
  - cat config/database.yml
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rspec spec