# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb56016a8d0c2c9b4ae99f3f9db98ebc96285b58dda4e03e53c91c0b5955c98841042a1924697415d6c97054f6b67a33cc38da67967832541d1b5127621ac0dc

test:
  secret_key_base: aa4a1c56f98cacc483be3d3ead293bcfafae7c692e2a970537b22f98823296ee0c960702d85bc2b77e7692a0e0a1b53580bcee93cc1083195e45519ca2c6d423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
